src/FTF/AttendeeBundle/Entity/Speaker.php
<?php

namespace FTF\AttendeeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * FTF\AttendeeBundle\Entity\Organizator
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="FTF\AttendeeBundle\Entity\SpeakerRepository")
 */
class Speaker
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;
    
    /**
     * @ORM\ManyToOne(targetEntity="Event")
     * @ORM\JoinColumn(name="event_id", referencedColumnName="id")
     */
    private $event;
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function setUser(User $user)
    {
        $this->user = $user;
    }
    
    public function setEvent(Event $event)
    {
        $this->event = $event;
    }
    
    public function getName()
    {
        return $this->user->getName();
    }
    
    public function getSurname()
    {
        return $this->user->getSurname();
    }
    
    public function getTwitter()
    {
        return $this->user->getTwitter();
    }
    
    public function getTwitterid()
    {
        return $this->user->getTwitterid();
    }
    
    public function getRole()
    {
        return 'Speaker';
    }
}

src/FTF/AttendeeBundle/Controller/DefaultController.php
<?php

namespace FTF\AttendeeBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Monolog\Handler\StreamHandler;
use Monolog\Logger;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="index")
     * @Route("/search", name="index_search")
     * @Method("get")
     * @Template()
     * @Cache(expires="+1 hours")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getEntityManager();
        $event = $em->getRepository('FTFAttendeeBundle:Event')
                ->findOneByName('FTF 2012');
        $attendees = $em->getRepository('FTFAttendeeBundle:Attendee')
                ->findByEvent($event);
        $organizators = $em->getRepository('FTFAttendeeBundle:Organizator')
                ->findByEvent($event->getId());
        $speakers = $em->getRepository('FTFAttendeeBundle:Speaker')
                ->findByEvent($event->getId());
        $users = array_merge($attendees, $organizators, $speakers);
        
        usort($users, function ($a, $b){
            return strcmp(strtolower($a->getTwitter()), strtolower($b->getTwitter()));
        });
        
        //shuffle($users);
        return array('attendees' => $users);
    }
    
    private function getFollowers($username)
    {
        if($content = file_get_contents('https://api.twitter.com/1/followers/ids.json?screen_name=' . $username)) {
            $followers = json_decode($content);
            return $followers->ids;
        }else{
            
            $kernel = $this->get('kernel');
            $logger = $this->get('logger');
            $logger->pushHandler(new StreamHandler($kernel->getLogDir() . '/twitter.log', Logger::INFO));
            $logger->err('Reached Limit loooking for ['.$username.']');
            
            return false;
        }
    }                
    
    private function getFriends($username)
    {
        if($content = file_get_contents('https://api.twitter.com/1/friends/ids.json?screen_name=' . $username)) {
            $followers = json_decode($content);
            return $followers->ids;
        }else{
            
            $kernel = $this->get('kernel');
            $logger = $this->get('logger');
            $logger->pushHandler(new StreamHandler($kernel->getLogDir() . '/twitter.log', Logger::INFO));
            $logger->err('Reached Limit loooking for ['.$username.']');
            
            return false;
        }
    }                
    
    /**
     * @Route("/search", name="search")
     * @Method("post")
     * @Template()
     */
    public function searchAction()
    {
        $kernel = $this->get('kernel');
        $request = $this->get('request');
        $username = $request->request->get('username');
        
        $logger = $this->get('logger');
        $logger->pushHandler(new StreamHandler($kernel->getLogDir() . '/twitter.log', Logger::INFO));
        $logger->info($username);
        
        if($username){
            return array(
                'username' => $username,
            );
        }else{
            return $this->redirect($this->generateUrl('index'));   
        }
    }
    
    /**
     * @Route("/ajax/search/{username}", name="ajax")
     * @Template()
     * @Cache(expires="+1 hours")
     */
    public function ajaxAction($username)
    {
        if(substr($username, 0, 1) == '@'){
            $username = substr($username, 1);
        }
        $followers = $this->getFollowers($username);
        $friends = $this->getFriends($username);
        if($followers == false or $friends == false){
            return array(
                'attendees' => array(),
                'username' => $username,
                'error' => true
            );
        }
        
        $em = $this->getDoctrine()->getEntityManager();
        $event = $em->getRepository('FTFAttendeeBundle:Event')
                ->findOneByName('FTF 2012');
        
        for($i=0;$i<2; $i++){
            if($i == 0) $users = $followers;
            else $users = $friends;
            $attendees = $em->getRepository('FTFAttendeeBundle:Attendee')
                    ->findAllByTwitteridAndEvent($users, $event);
            $organizators = $em->getRepository('FTFAttendeeBundle:Organizator')
                    ->findAllByTwitteridAndEvent($users, $event);
            $speakers = $em->getRepository('FTFAttendeeBundle:Speaker')
                    ->findAllByTwitteridAndEvent($users, $event);
            $users = array_merge($attendees, $organizators, $speakers);
            usort($users, function ($a, $b){
                return strcmp(strtolower($a->getTwitter()), strtolower($b->getTwitter()));
            });
            if($i == 0) $followers = $users;
            else $friends = $users;
        }
        $user = $em->getRepository('FTFAttendeeBundle:User')->findOneByTwitter($username);
        
        $param = array(
            'followers' => $followers,
            'friends' => $friends,
            'username' => $username,
            'registered' => (bool)$user,
            'error' => false
        );
        
        return $this->render('FTFAttendeeBundle:Default:ajax.html.twig', $param);
        
        $response = $this->render('FTFAttendeeBundle:Default:ajax.html.twig', $param);
        $response->setETag(md5($response->getContent()));
        $response->setPublic();
        $response->setSharedMaxAge(60*60*24);
        $response->setMaxAge(60*60*24);

        return $response;
    }
}

src/FTF/AttendeeBundle/Resources/views/Default/_users.html.twig
<ul class="friends">
{% for user in attendees %}
    <li class="friend">
        {#<span class="role role_{{ user.role }}">{{ user.role }}</span> #}
        <a class="avatar external" href="http://twitter.com/{{ user.twitter }}">
                <img class="avatar" src="http://api.twitter.com/1/users/profile_image?screen_name={{ user.twitter }}&size=bigger">
        </a>
        <a class="name external" href="http://www.twitter.com/{{ user.twitter }}" title="{{ user.name }} {{ user.surname }}">{{ user.name }} {{ user.surname }}</a>
        <span class="handle" title="@{{ user.twitter }}">@{{ user.twitter }}</span>
    </li>
{% endfor %}
</ul>

src/FTF/AttendeeBundle/Resources/views/Default/ajax.html.twig
{%block content %}
    {% if error %}
        <div class="m-title">
            <h1 class="title friends">Sorry. We reached the limit of request for twitter or user <b>@{{ username }}</b> doesn't exists. Please try again in 1 hour.</h1>
        </div>
    {% else %}
        <div class="m-title">
            <h1 class="title friends">Check who's coming</h1>
        </div>

        <div class="m-friends">
            <p>Friends and Followers of <strong>@{{ username }}</strong> at The Treasure of Frontend Island </p>
            
            {% if friends|length + followers|length <= 0 %}
                <div class="intro">
                    <p>It looks like none of the Friends and Followers of <strong>@{{ username }}</strong> is partecipating at The Treasure of Frontend Island.</p>
                    <p>Do you want to try with another Twitter id?</p>
                </div>
            {%else %}
                
                {% if friends|length > 0 %}
                    <h2>Your Friends</h2>
                    {% include 'FTFAttendeeBundle:Default:_users.html.twig' with {'attendees': friends } %}
                {% endif %}
                {% if followers|length > 0 %}
                    <h2>Your Followers</h2>
                    {% include 'FTFAttendeeBundle:Default:_users.html.twig' with {'attendees': followers } %}
                {% endif %}
            {% endif %}

            {% include 'FTFAttendeeBundle::_form.html.twig' %}

            {% if not registered %}
                <div class="m-title">
                    <h1 class="title speakers">No ticket yet?</h1>
                </div>

                <div class="ticket">
                    <p>Still haven't got a ticket? What are you waiting to <strong>join your friends</strong> in their exciting journey to the Frontend Island?</p>
                    <p>And remember to spread the word quickly, <strong>time is running up</strong>!</p>
                    <a class="item-button" href="http://2012.fromthefront.it/#cart">Get your ticket now!</a>
                </div>
            {% endif %}
        </div>
    {% endif %}
    
{% endblock %}

src/FTF/AttendeeBundle/Resources/views/Default/index.html.twig
{% extends 'FTFAttendeeBundle::layout.html.twig' %}

{%block content %}
    <div class="m-title">
        <h1 class="title friends">Check who's coming</h1>
    </div>

    <div class="m-friends">
        <div class="intro">
            <p>A conference is not only a frontal lesson made by awesome teachers, a conference is an important networking opportunity: get in touch with people you follow online, drink something with your web dev hero or firmly shake your hand to someone you engaged a rough flame with ;)</p>
            <p>Enter your Twitter handle and discover whom of your friends or followers is coming to The Treasure of Frontend Island!</p>
        </div>
        {% include 'FTFAttendeeBundle::_form.html.twig' %}
        {% include 'FTFAttendeeBundle:Default:_users.html.twig' %}
    </div>
{% endblock %}
            
{% block enum %}
    <small>{{ attendees|length }} with Twitter</small>
{% endblock %}

src/FTF/AttendeeBundle/Resources/views/Default/search.html.twig
{% extends 'FTFAttendeeBundle::layout.html.twig' %}

{%block content %}
    <div id="results">
        <div class="well">
            <h3>Searching <b>@{{ username }}</b> friends and followers ...</h3>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            $.get('{{ path('ajax', { 'username': username }) }}', function(data) {
                $('#results').html(data);
            });
        });
    </script>
{% endblock %}